### ISSUE TITLE
Implement Get user info 

### ISSUE THREAD

**Issue by artus15** [artus15/ECSE428-FitGarage#4]
[.feature file](https://github.com/artus15/ECSE428-FitGarage/blob/main/documentation/ID003_Get_user_info.feature)

End points: GET
Parameters: Id, name
Response: Users in JSON format

User story:
"As an admin
I want to retrieve all information from a user
So I can contact him"

**Comment by Czarlhd** [comment]
Created get user by id, by email, and all users
