### ISSUE TITLE
Implement Change user attributes

### ISSUE THREAD

**Issue by artus15** [artus15/ECSE428-FitGarage#6]
[.feature file](https://github.com/artus15/ECSE428-FitGarage/blob/main/documentation/ID005_Change_user_attribute.feature)

End points: PATCH
Parameters: name,email,isAdmin
Response: fields which changed

User story:
"As an active user
I want to change my email address
So I can receive notifications on my main address"

**Comment by Czarlhd** [comment]
Created api to change user attributes successfully !
